### ISSUE TITLE
Save won't load

### ISSUE THREAD

**Issue by Bandypams** [Yagisan/The-Bustling-Valley#1]
I was playing for a couple of hours this afternoon, all going well.  I went to go back into the save and it will not load, just sits at Black screen with loading... in bottom left infinitely  Have attached the save zipped up here if you want/need to take a look at it.
[Bandypams_288184255.zip](https://github.com/Yagisan/The-Bustling-Valley/files/6957041/Bandypams_288184255.zip)

I had this issue with the other SDV modlist, disabling 1 of SDV or Ridgeside Village seemed to be the fix in that situation. 

If you need anything else, please let me know, I'd love to see another good SDV modlist going.

**Comment by Yagisan** [comment]
I'm suspecting you had an Out of Memory error on load, as this worked for me. SVE is a potential candidate for removal as it's commonly involved in these. I can only suggest trying to load it again.

![Bandypams](https://user-images.githubusercontent.com/172080/128779497-8da50160-a505-472a-b14c-090cf42b9e6d.png)

**Comment by Bandypams** [comment]
Cheers Yagisan.  I've retried a few times but no luck but I will look into the Memory thing you suggested. I am brand new to modding SDV so was not aware this was a thing.  Thanks again.
