### ISSUE TITLE
Memory issues. Will not load after restart. 

### ISSUE THREAD

**Issue by psychonot23** [Yagisan/The-Bustling-Valley#5]
0.5.10
Modlist not modified. 

https://smapi.io/log/27502dfd67644e11b26f933ca70162f5

Have been playing the modpack for a couple days. Computer was experiencing memory issues (100% usage) namely hanging when walking, speaking to villagers, and transitioning from one location to another. These issues worsened as I progressed further into the game particularly when carrying lots of the added forages. 

I closed the game to see if reopening it would ease these issues as I have a tendency to just keep games open for days at a time. After selecting the proper save file the game goes to the loading screen for about 6 seconds then crashes.

**Comment by Yagisan** [comment]
Please reupload your SMAPI log file. Your log is reported as invalid.

You should be aware that Stardew Valley 1.5.6 loads all assets into memory when starting the game, as this list requires **6GB** (six gigabytes) of RAM to load. The amount of memory required to play increases the further you get into each season. SpriteMaster (enabled by default) attempts to unload unused assets to reduce ram use.

**Comment by psychonot23** [comment]
I have 16GB of RAM.

As it stands SMAPI log parser returns the following error on my SMAPI-latest.txt

> The page was not displayed because the request entity is too large. 

I can upload the log elsewhere if required. 

These are the logs that I have under \AppData\Roaming\StardewValley\ErrorLogs

![SDV_Logs](https://user-images.githubusercontent.com/128005008/225649425-36d13d0b-150f-48bd-8bd8-c8009a158ef6.PNG)

**Comment by Yagisan** [comment]
7zip up SMAPI-latest - but that's honestly one of the biggest log files I have ever seen. Should be able to attach it here.

**Comment by psychonot23** [comment]
Regardless even if the save isn't salvageable I hope it provides some insight into potential future problems.  Playing this made me feel like I was playing it again for the first time which is a major feat. 

Many thanks. 

[SMAPI-latest-copy.zip](https://github.com/Yagisan/The-Bustling-Valley/files/10994152/SMAPI-latest-copy.zip)

**Comment by Yagisan** [comment]
TBV 0.6.x has been released, which has a different list makeup. As such this bug is no longer applicable.
