### ISSUE TITLE
[BUG] Minor visual bug - Sheila, Joel and Gregory not using halloween sprites(From Boarding House and Bus Stop)

### ISSUE THREAD

**Issue by Dexter5716** [Yagisan/The-Bustling-Valley#6]
**Attach your SMAPI Log**
[SMAPI-latest.txt](https://github.com/Yagisan/The-Bustling-Valley/files/12176683/SMAPI-latest.txt)

**Describe the bug**
All 3 of the NPCs from Boarding House and Bus Stop aren't using their halloween sprite and are using the normal one. The outfit *does* show up in their character portrait when talking to them however.

**To Reproduce**
Talk to the NPCs during Spirit's Eve event.
NPC will be wearing their normal outfit, but their portrait will show their halloween outfit.

**Expected behavior**
Sprite outfit should match their halloween protrait.

**Screenshots**
--

**Modlist version**
0.6.2

**Did you add any additional mods?**
No. SpriteMaster is disabled.

**Comment by Yagisan** [comment]
This is odd. The default settings are to use Seasonal Outfits for both Boarding House and the replacement portraits.

The sprites exist, and the code appears correct. I'll dig into this further once I have a save ready for Spirit's Eve.

**Comment by Yagisan** [comment]
No longer in 0.7.x
