### ISSUE TITLE
[BUG] Furniture style changes when being moved

### ISSUE THREAD

**Issue by Durgenage** [Yagisan/The-Bustling-Valley#8]
[SMAPI-latest.txt](https://github.com/Yagisan/The-Bustling-Valley/files/15192172/SMAPI-latest.txt)

Moving default furniture on a new farm seems to swap the style

To reproduce just attempt to move furniture that spawned with your new farm. I have not tested with newly purchased / obtained furniture

https://github.com/Yagisan/The-Bustling-Valley/assets/96037567/6bc7f0d4-6578-4494-a12e-985d07f65450

This is on version 0.7.1

The only list modification was turning off 'Clear Glasses' as originally suggested. The issue happens with that mod on or off

**Comment by Yagisan** [comment]
Fixed in 0.7.2 - the default configuration for Alternative Textures and Floor, Building, and Furniture randomisation is now false. Use the paint tool to change them.
