### ISSUE TITLE
[BUG] Special Projects Board In Front Of Lewis's House Covered By Bush

### ISSUE THREAD

**Issue by hookemravens** [Yagisan/The-Bustling-Valley#9]
**Attach your SMAPI Log**

Please attach your SMAPI log to this bug report.
Reports without a SMAPI log will be *ignored and closed as invalid.*

1. Press the `Windows` and `R` buttons at the same time.
2. In the 'run' box that appears, enter this exact text:
3. The log file is `SMAPI-crash.txt` if it exists, otherwise `SMAPI-latest.txt`

`[SMAPI-latest.txt](https://github.com/user-attachments/files/15519255/SMAPI-latest.txt)`

**Describe the bug**

The special projects board in front of Lewis's house is covered by a bush

**To Reproduce**

1. Go to special projects board in front of Lewis's house, cannot interact with the board
2. See error

**Expected behavior**

No bush covering special projects board

**Screenshots**

Screenshot attached

**Modlist version**

0.7.4

**Did you add any additional mods?**

No added mods

![Stardew Valley 1 6 8 - running SMAPI 4 0 8 with 233 mods 5_31_2024 3_37_50 PM](https://github.com/Yagisan/The-Bustling-Valley/assets/171390396/f84ae9bd-daa3-441d-87c6-e42abc685051)

**Comment by Yagisan** [comment]
The ability to chop down this bush has been available since TBV 0.7.6
